import type { Metadata } from 'next';
import { Source_Code_Pro, Abel } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';
import Footer from '@/components/footer/Footer';
import Container from '@/components/global/Container';

const abel = Abel({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-abel',
});
const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  variable: '--font-sourceCodePro',
});

export const metadata: Metadata = {
  title: 'Allerton Creek Farm | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${abel.variable} ${sourceCodePro.variable}`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
